<p>Welcome to Qaptured.com. Please read these terms and conditions carefully before using this Site. By accessing or using the Site and all of its services, you agree to be bound by these terms and conditions. In addition, when using these services, you shall be subject to any posted guidelines or rules applicable to such services. The provision of information and services on this Site by the owners and operators of Qaptured.com is subject to your agreement to the terms and conditions.</p>
<h5>Right to Change Terms and Conditions</h5>
<p>Qaptured® may, at any time and from time to time, change these terms and conditions. Any changes to these terms and conditions will be effective immediately upon posting of the changed terms and conditions on the Site. You agree to review these terms and conditions periodically, and use of the Site following any such change constitutes your agreement to follow and be bound by the terms and conditions as changed.</p>
<p><b>ANY PARTICIPATION IN THIS SITE WILL CONSTITUTE ACCEPTANCE OF THIS AGREEMENT. IF YOU DO NOT AGREE TO ABIDE BY THE ABOVE, PLEASE DO NOT USE THIS SITE.</b></p>
<h4>Online Privacy Policy</h4>
<ul>
  <li> <b>- What Personal Information We Collect</b>
    <p>Qaptured.com collects your personal information online when you voluntarily provide it to us. If you choose to register online, we ask you to provide limited personal information, such as your name, address, telephone number and/or email address. We also collect information that will allow you to establish a username and password if you would like to do that. We use the information that you provide for such purposes as responding to your requests, customizing and enhancing future browsing for you, improving our site, and communicating with you.</p>
  </li>
  <li> <b>- Disclosure of Personal Information to Third Parties</b>
    <p>We will not disclose any personal information to any third party (excluding our contractors to whom we may provide such information for the limited purpose of providing services to us and who are obligated to keep the information confidential), unless (1) you have authorized us to do so; (2) we are legally required to do so, for example, in response to a subpoena, court order or other legal process and/or, (3) it is necessary to protect our property rights related to this website. We also may share aggregate, non-personal information about website usage with unaffiliated third parties. This aggregate information does not contain any personal information about our users.</p>
  </li>
  <li> <b>- Third Party Sites</b>
    <p>We want to provide our users and site visitors valuable information and services. Featured services and other site content within the Qaptured® site may contain links to or integrations with other sites (e.g., Facebook, Twitter, IMDB, YouTube). Qaptured does not control and is not responsible for practices of any third-party websites. The use of these technologies by these third parties is subject to their own privacy policies and is not covered by this privacy statement. </p>
  </li>
  <li> <b>- Your Account</b>
    <p>If you use any Qaptured® Service, you are responsible for maintaining the confidentiality of log-in information and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. Qaptured reserves the right to refuse service, terminate accounts, or remove or edit contents in its sole discretion.</p>
  </li>
</ul>
<h5>Content Boundaries and Use of Qaptured</h5>
<p> In order to provide the Qaptured service and the ability to communicate and stay connected with others, there are some limitations on the type of content that can be posted and published (including, but not limited to, commenting, sharing, suggesting, rating and communicating) with Qaptured. These limitations comply with legal requirements and make Qaptured a better experience for all.</p>
<ul>
  <li> <b>• Impersonation: </b>You may not use a false e-mail address, impersonate others through the Qaptured service in a manner that does or is intended to mislead, confuse, or deceive others. Qaptured reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content. </li>
  <li> <b>• Trademark: </b>We reserve the right to restrict the use of certain user names and profile URLs on behalf of businesses or individuals that hold legal claim or trademark on those user names or profile URLs. Accounts using business names and/or logos to mislead others will be permanently suspended. </li>
  <li> <b>• Privacy: </b>You may not publish or post other people's private and confidential information, such as credit card numbers, street address or Social Security/National Identity numbers, without their express authorization and permission. </li>
  <li> <b>• Profile Images & Covers: </b>You may not use obscene, pornographic, invasive of privacy or images that may be disturbing to some viewers in your profile and cover photo. </li>
  <li> <b>• Spam: </b>Users may not post content injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of “spam.” </li>
</ul>
<h4>Disclaimer of Warranties and Limitation of Liability</h4>
<p><b> THE QAPTURED SERVICES AND ALL INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) AND OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE QAPTURED SERVICES ARE PROVIDED BY QAPTURED ON AN "AS IS" AND "AS AVAILABLE" BASIS. QAPTURED MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE QAPTURED SERVICES OR THE INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE QAPTURED SERVICES. YOU EXPRESSLY AGREE THAT YOUR USE OF THE QAPTURED SERVICES IS AT YOUR SOLE RISK. QAPTURED RESERVES THE RIGHT TO WITHDRAW ANY QAPTURED SERVICE OR DELETE ANY INFORMATION FROM THE QAPTURED SERVICES AT ANY TIME IN ITS DISCRETION.</b></p>